GET http://localhost:3003/users
###
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "email": "erithrina@mail.com",
    "password": "abcdef",
    "role": "admin",
    "cep": "25655090",
    "number": "484",
    "complement": "casa 3"
}
###
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "delonix@mail.com",
    "password": "123456"
 
}