GET http://localhost:3003/users
###
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "email": "strongylodon@mail.com",
    "password": "123456"
}
###
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "moka@mail.com",
    "password": "123456"
 
}